### PR TITLE
Added code-of-conduct.md file

### LINKED ISSUE #5: Create Code of Conduct for this project
Something similar to Contributor Covenant, version 1.4:
https://www.contributor-covenant.org/version/1/4/code-of-conduct/

Or the latest version 2.1:
https://www.contributor-covenant.org/version/2/1/code_of_conduct/

### PR DESCRIPTION
**Pull request by Pariharx7**
```diff
+ Code-of-Conduct.md was added
```

### CODE REVIEW

**Comment by adrianyorke** [comment]
One small change: the file must be named **CODE_OF_CONDUCT.md**

Not my naming standard. This is so github (and other repository platforms) recognise this standard/common document has been added to this project.

The text looks good though, let's go with that wording. Once you have renamed the file I will merge it into the main repo.

**Comment by Pariharx7** [comment]
Renamed the file to CODE_OF_CONDUCT.md

**Comment by adrianyorke** [comment]
Many thanks, looks good. I will merge this PR and add you to the Contributors.

**Comment by adrianyorke** [comment]
@all-contributors please add @Pariharx7  for code, maintenance

**Comment by Pariharx7** [comment]
Thanks

**Pull request merged**
